/**
 * Pure logic for the `subagent` (code_index) tool: the prompt given to the
 * nested read-only agent, and extracting its final answer back out of the
 * SDK's message list. No pi/SDK imports here, so it unit-tests standalone;
 * the actual `createAgentSession` orchestration lives in
 * extensions/subagent.ts (a real nested agent run, not something to mock in
 * a unit test -- see that file's own docstring).
 */

export const INDEX_RELATIVE_PATH = ".pi/index/CODEINDEX.md";

export function buildIndexPrompt(focus?: string): string {
  const scope = focus
    ? `Focus on this area of the codebase: ${focus}.`
    : "Cover the whole repository.";
  return [
    "You are building a CODE INDEX for another agent to use as a fast lookup map.",
    scope,
    "Explore the repository (read/grep/find/ls only -- do not run bash or edit anything).",
    "You MUST call ls/find to enumerate real files and read/grep to confirm what they contain",
    "BEFORE listing them -- never guess a filename or description from naming conventions or",
    "typical project layouts. If unsure what a file does, open it first. An index entry for a",
    "file you did not actually see is worse than no entry.",
    "Output ONLY a markdown list, one line per file or tightly-related file group, in the form:",
    "`- path/to/file.ext — one-line description of what it contains / when to read it`",
    "Group by directory with a `## path/to/dir/` heading above its files when that's clearer.",
    "Be terse (a pointer, not a summary): a reader should know WHERE to look, not the file's",
    "full contents. Skip generated/vendored/lock files, node_modules, __pycache__, .git.",
    "Do not include any prose before or after the list.",
  ].join(" ");
}

/** Structural subset of an SDK `AgentMessage` -- deliberately loose (no
 *  dependency on @earendil-works/pi-agent-core's real type) so this stays
 *  unit-testable without the SDK installed. */
export interface MinimalMessage {
  role: string;
  content?: Array<{ type: string; text?: string }> | string;
}

/** The last assistant message's text content, joined -- "" if none found. */
export function extractAssistantText(messages: MinimalMessage[]): string {
  for (let i = messages.length - 1; i >= 0; i--) {
    const m = messages[i];
    if (m.role !== "assistant") continue;
    if (typeof m.content === "string") return m.content;
    const texts = (m.content ?? [])
      .filter((c): c is { type: string; text: string } => c.type === "text" && !!c.text)
      .map((c) => c.text);
    return texts.join("\n");
  }
  return "";
}

export function renderIndexFile(
  body: string,
  opts: { focus?: string; generatedAt?: Date } = {},
): string {
  const when = (opts.generatedAt ?? new Date()).toISOString();
  const header = [
    "<!-- generated by the pi `subagent` (code_index) tool -->",
    `<!-- generated: ${when}${opts.focus ? ` | focus: ${opts.focus}` : ""} -->`,
    "",
  ].join("\n");
  return `${header}${body.trim()}\n`;
}
