import { describe, expect, it } from "vitest";
import { buildIndexPrompt, extractAssistantText, renderIndexFile } from "../src/codeIndex";

describe("buildIndexPrompt", () => {
  it("covers the whole repo when no focus is given", () => {
    const p = buildIndexPrompt();
    expect(p).toMatch(/Cover the whole repository/);
    expect(p).not.toMatch(/Focus on this area/);
  });

  it("narrows scope when a focus is given", () => {
    const p = buildIndexPrompt("the gateway and providers");
    expect(p).toMatch(/Focus on this area of the codebase: the gateway and providers/);
  });

  it("instructs read-only, terse, markdown-list output", () => {
    const p = buildIndexPrompt();
    expect(p).toMatch(/do not run bash or edit anything/i);
    expect(p).toMatch(/markdown list/i);
  });
});

describe("extractAssistantText", () => {
  it("returns the last assistant message's joined text blocks", () => {
    const text = extractAssistantText([
      { role: "user", content: "hi" },
      { role: "assistant", content: [{ type: "text", text: "first" }] },
      { role: "toolResult", content: [{ type: "text", text: "ignored" }] },
      {
        role: "assistant",
        content: [
          { type: "text", text: "a" },
          { type: "text", text: "b" },
        ],
      },
    ]);
    expect(text).toBe("a\nb");
  });

  it("handles a plain string content assistant message", () => {
    expect(extractAssistantText([{ role: "assistant", content: "plain" }])).toBe("plain");
  });

  it("skips non-text content blocks", () => {
    const text = extractAssistantText([
      { role: "assistant", content: [{ type: "toolCall" }, { type: "text", text: "only this" }] },
    ]);
    expect(text).toBe("only this");
  });

  it("returns empty string when there is no assistant message", () => {
    expect(extractAssistantText([{ role: "user", content: "hi" }])).toBe("");
    expect(extractAssistantText([])).toBe("");
  });
});

describe("renderIndexFile", () => {
  it("wraps the body with a header comment including the focus", () => {
    const out = renderIndexFile("- a.md — x", {
      focus: "gateway",
      generatedAt: new Date("2026-01-01T00:00:00Z"),
    });
    expect(out).toMatch(/generated by the pi `subagent`/);
    expect(out).toMatch(/focus: gateway/);
    expect(out).toMatch(/2026-01-01T00:00:00\.000Z/);
    expect(out.endsWith("- a.md — x\n")).toBe(true);
  });

  it("omits the focus fragment when none is given", () => {
    const out = renderIndexFile("body");
    expect(out).not.toMatch(/focus:/);
  });

  it("trims trailing whitespace from the body before the final newline", () => {
    const out = renderIndexFile("- a.md — x\n\n\n");
    expect(out.endsWith("- a.md — x\n")).toBe(true);
  });
});
